### ISSUE TITLE
Имеется ли валидатор под стандартные проверки на стороне php?

### ISSUE THREAD

**Issue by WalkWeb** [volmir/dalt-framework#3]
И снова я :-)

Просмотрел код на наличие валидатора под стандартные проверки на стороне php - не нашел. Как понимаю, его нет в вашем фреймворке?

**Comment by volmir** [comment]
Да. все верно. Таких валидаторов нет.


15 марта 2018, 14:06:32, от WalkWeb <notifications@github.com>: 


И снова я :-)

Просмотрел код на наличие валидатора под стандартные проверки на стороне php - не нашел. Как понимаю, его нет в вашем фреймворке?

**Comment by WalkWeb** [comment]
Понятно.

Странно как-то получается. Пилю свой микро-фреймворк (пока там 1300 строк), ну и смотрю как другие микрофреймворки сделаны - по Dalt Framework (5200 строк) видно, что ваш уровень выше моего, но анализирую функционал - защиты от csrf нет, валидатора под стандартные проверки нет... не могу понять, почему с одной стороны наворотов больше, а практичного функционала (ну, лично с моей субъективной точки зрения) меньше.

Возможно причина в целях. Я свой микро-фреймворк делаю для реально работающего сайта с посещаемостью 10 000+ человек в сутки, по этому меня в первую очередь заботит безопасность и производительность.

Вам же, возможно было просто интересно сделать свой фреймворк.

Верно?

P.S. Просьба не воспринимать мои слова как попытку похвалиться, по коду видно, что ваш уровень весьма выше моего.

**Comment by volmir** [comment]
Здравствуйте!


Скорее всего область прикладного и теоретического программирования настолько широка и глубока, что её комплексно познать довольно сложно.
Вот поэтому и идут специализации и ответвления.
Судя по вашему комментарию, ваш уровень как специалиста достаточно высок.
Так же практическая направленность вашей деятельности прибавляет и увеличивает общественную полезность вашей работы.


Вначале цели свои я формулировал как обучение и повышение квалификации. По мере работы над фреймворком захотелось добавить практическо-ориентированные модули и функциональность. Но, так как рабочего, живого проекта не было (на чем все тестировать; познавать, какие задачи ставятся жизнью и текущей реальностью) - проект перешел в архив.


Спасибо вам за подробный анализ и комментарий.


16 марта 2018, 09:35:42, от WalkWeb <notifications@github.com>: 


Понятно.

Странно как-то получается. Пилю свой микро-фреймворк (пока там 1300 строк), ну и смотрю как другие микрофреймворки сделаны - по Dalt Framework (5200 строк) видно, что ваш уровень выше моего, но анализирую функционал - csrf нет, валидатора под стандартные проверки нет... не могу понять, почему с одной стороны наворотов больше, а практичного функционала (ну, лично с моей субъективной точки зрения) меньше.

Возможно причина в целях. Я свой микро-фреймворк делаю для реально работающего сайта с посещаемостью 10 000+ человек в сутки, по этому меня в первую очередь заботит безопасность и производительность.

Вам же, возможно было просто интересно сделать свой фреймворк.

Верно?

P.S. Просьба не воспринимать мои слова как попытку похвалиться, по коду видно, что ваш уровень весьма выше моего.
